arch = { packages = [
  "aerc",
  "android-tools",
  "apitrace",
  "base-devel",
  "bash-completion",
  "binutils",
  "bloaty",
  "bpftrace",
  "ccache",
  "clang",
  "cmake",
  "curl",
  "fd",
  "fq",
  "gcc",
  "gdb",
  "git",
  "git-filter-repo",
  "git-lfs",
  "github-cli",
  "glibc-locales",
  "htop",
  "imagemagick",
  "jq",
  "konsole",
  "less",
  "lftp",
  "lsof",
  "ltrace",
  "man-db",
  "man-pages",
  "meson",
  "metapac",
  "moreutils",
  "mtr",
  "ncdu",
  "neovim",
  "nmap",
  "numactl",
  "openssh",
  "ouch",
  "patchelf",
  "perf",
  "pkgconf",
  "plocate",
  "postgresql",
  "progress",
  "rclone",
  "ripgrep",
  "rizin",
  "rsync",
  "ruff",
  "rustup",
  "rz-cutter",
  "skopeo",
  "strace",
  "sudo",
  "tcpdump",
  "time",
  "traceroute",
  "tree",
  "tree-sitter-cli",
  "ttf-hack",
  "uv",
  "wget",
  "which",
  "wireshark-cli",
  "wl-clipboard",
  "yt-dlp",
] }
