arch = { packages = [
  "archinstall",
  "base",
  "cpupower",
  "cups",
  "distrobox",
  "dolphin",
  "ecryptfs-utils",
  "flatpak",
  "flatpak-kcm",
  "framework-system",
  "fwupd",
  "icaclient",
  "intel-ucode",
  "kdeconnect",
  "mesa",
  "nvidia-open",
  "nvidia-prime",
  "nvidia-utils",
  "partitionmanager",
  "paru",
  "plasma-meta",
  "podman",
  "reflector",
  "vulkan-radeon",
  "webkit2gtk-bin",
  "wireguard-tools",
] }
flatpak = { repos = [
  { name = "system:flathub", options = { url = "https://dl.flathub.org/repo/" } },
], packages = [
  { name = "system:com.borgbase.Vorta", options = { remote = "flathub" } },
] }
